apiVersion: apps/v1
kind: Deployment
metadata:
  name: azhar
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: azhar
  template:
    metadata:
      labels:
        app: azhar
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v5
          name: azhar
          ports:
            - containerPort: 80
